import{a as g,S as b,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const c of s.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const L="51513687-083115f87febea1a11bb9e180",w="https://pixabay.com/api/",v=15;async function S(o,t=1){const r={key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:v};return(await g.get(w,{params:r})).data}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".load-more"),q=new b(".gallery a",{captionsData:"alt",captionDelay:250});function P(o){const t=o.map(r=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" class="gallery-img" />
      </a>
      <div class="info">
        <p class="info-descr">  <b>Likes:</b> ${r.likes}</p>
        <p class="info-descr"> <b>Views:</b> ${r.views}</p>
        <p class="info-descr">  <b>Comments:</b> ${r.comments}</p>
        <p class="info-descr"> <b>Downloads:</b> ${r.downloads}</p>
      </div>
    </li>
  `).join("");u.insertAdjacentHTML("beforeend",t),q.refresh()}function B(){u.innerHTML=""}function M(){f.classList.remove("hidden")}function $(){f.classList.add("hidden")}function E(){m.classList.remove("hidden")}function y(){m.classList.add("hidden")}const h=document.querySelector(".form"),O=h.elements["search-text"],x=document.querySelector(".load-more");let l="",n=1,d=0;h.addEventListener("submit",async o=>{if(o.preventDefault(),l=O.value.trim(),!l){a.warning({message:"Please enter a search query!"});return}B(),y(),n=1,await p()});x.addEventListener("click",async()=>{n+=1,await p(!0)});async function p(o=!1){M();try{const t=await S(l,n);if(d=t.totalHits,!t.hits.length){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}P(t.hits);const r=Math.ceil(d/15);n<r?E():(y(),a.info({message:"We're sorry, but you've reached the end of search results."})),o&&A()}catch{a.error({message:"Something went wrong. Please try again later."})}finally{$()}}function A(){const o=document.querySelector(".gallery a");if(o){const t=o.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
