import{a as w,S as P,i as a}from"./assets/vendor-5YrzWRhu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function c(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const v="YOUR_PIXABAY_API_KEY",S="https://pixabay.com/api/",q=15;async function u(r,t=1){const o={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:q};return(await w.get(S,{params:o})).data}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),B=new P(".gallery a",{captionsData:"alt",captionDelay:250});function h(r){const t=r.map(o=>`
        <li class="gallery-item">
          <a href="${o.largeImageURL}">
            <img src="${o.webformatURL}" alt="${o.tags}" />
          </a>
          <div class="info">
            <p><b>Likes:</b> ${o.likes}</p>
            <p><b>Views:</b> ${o.views}</p>
            <p><b>Comments:</b> ${o.comments}</p>
            <p><b>Downloads:</b> ${o.downloads}</p>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function A(){f.innerHTML=""}function p(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function E(){y.classList.remove("hidden")}function L(){y.classList.add("hidden")}const b=document.querySelector(".form"),M=b.elements["search-text"],_=document.querySelector(".load-more");let i="",n=1,d=0;b.addEventListener("submit",async r=>{if(r.preventDefault(),i=M.value.trim(),!i){a.warning({message:"Please enter a search query!"});return}n=1,A(),L(),p();try{const t=await u(i,n);if(d=t.totalHits,!t.hits.length){a.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits),d>n*15&&E()}catch{a.error({message:"Something went wrong. Please try again later."})}finally{g()}});_.addEventListener("click",async()=>{n+=1,p();try{const r=await u(i,n);h(r.hits),$();const t=Math.ceil(d/15);n>=t&&(L(),a.info({message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({message:"Failed to load more images."})}finally{g()}});function $(){const{height:r}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
